theme: jekyll-theme-cayman
title: "Using the American Community Survey API"
description: "Thomas Roca, Senior Data-scientist, @Microsoft - Data Science & Analytics team"
logo: /assets/img/logo.png
author: "Thomas Roca, PhD"
